apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytest
  namespace: default
spec:
  replicas: 2
  imagePullSecrets:
  - name: ghcr-secret
  selector:
    matchLabels:
      app: pytest
  template:
    metadata:
      labels:
        app: pytest
    spec:
      containers:
      - name: pytest
        image: ghcr.io/gustavonlorenzo/test:1.0
