on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build_image:
    runs-on: self-hosted
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Build docker image
        run: |
          sudo docker build --file dockerfile --tag pytest:$RELEASE_VERSION .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: gustavonlorenzo@gmail.com
          password: ${{ secrets.GHCR_PAT }}

      - name: Docker Tag ang Push
        run: |
          docker tag pytest:$RELEASE_VERSION ghcr.io/gustavonlorenzo/pytest:$RELEASE_VERSION
          docker image push ghcr.io/gustavonlorenzo/pytest:$RELEASE_VERSION
      
      - name: update manifest
        run: ./update-release.sh $RELEASE_VERSION
      
      - name: commit new manifest
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master