on:
  push:
    #tags:
    #  - 'v*.*.*'
jobs:
  build_image:
    runs-on: self-hosted
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Build docker image
        run: |
          sudo docker build --file dockerfile --tag pytest:$RELEASE_VERSION .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: gustavonlorenzo@gmail.com
          password: ${{ secrets.GHCR_PAT }}

      - name: Docker Tag ang Push
        run: |
          docker tag pytest:$RELEASE_VERSION ghcr.io/gustavonlorenzo/pytest:$RELEASE_VERSION
          docker image push ghcr.io/gustavonlorenzo/pytest:$RELEASE_VERSION

      #- name: build_push
      #  env:
      #    GHCR_PAT: ${{ secrets.GHCR_PAT }}
      #  run: |
      #    sudo docker build --file dockerfile --tag pytest:$RELEASE_VERSION .
      #    echo $GHCR_PAT | sudo docker login ghcr.io -u gustavonlorenzo@gmail.com --password-stdin
      #    sudo docker tag pytest:$RELEASE_VERSION ghcr.io/gustavonlorenzo/pytest:$RELEASE_VERSION
      #    sudo docker image push ghcr.io/gustavonlorenzo/pytest:$RELEASE_VERSION
      
      - name: update manifest
        run: ./update-release.sh $RELEASE_VERSION
      
      - name: commit new manifest
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
##
##### For later review
##
##  build:
##    name: Build
##    needs: test
##    runs-on: ubuntu-latest
##    steps:

##
##      - name: Build and push the Docker image
##        uses: docker/build-push-action@v3
##        with:
##          push: true
##          tags: |
##            ghcr.io/username/package:latest
##            ghcr.io/username/package:${{ github.sha }}