#name: Docker Image CI
#
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#
#  build:
#
#    runs-on: self-hosted
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Build the Docker image
#      run: sudo docker build . --file dockerfile --tag pytest:$(date +%s)
#

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          docker build -t test:$RELEASE_VERSION .

