on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: build_push
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        run: |
          sudo docker build --file dockerfile --tag pytest:$RELEASE_VERSION .
          echo $GHCR_PAT | sudo docker login ghcr.io -u gustavonlorenzo@gmail.com --password-stdin
          sudo docker tag pytest:$RELEASE_VERSION ghcr.io/gustavonlorenzo/pytest:$RELEASE_VERSION
          sudo docker image push ghcr.io/gustavonlorenzo/pytest:$RELEASE_VERSION

